theme: minima
title: My Portfolio
author: Henry Woods
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  portfolio,resume

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
